INCLUDES	=
DEP_INTERNAL	=
DEP_EXTERNAL	=

LIBS		= applog.a
SRCS_applog	= assert.cpp internal.cpp module.cpp logger.cpp \
		  sink.cpp filter_sink.cpp ostream_sink.cpp

all:	$(LIBS)

include ../Makefile.inc
