INCLUDES	=
DEP_INTERNAL	= models rec dlibx
DEP_EXTERNAL	=

LIBS		= rec_dlib.a
SRCS_rec_dlib	= model.cpp model_load.cpp \
		  extract.cpp engine.cpp

all:	$(LIBS) $(EXCLUDED) test_lib

include ../Makefile.inc
