INCLUDES	=
DEP_INTERNAL	= render rec_dlib det_dlib
DEP_EXTERNAL	=

LIBS		= tools.a
SRCS_tools	= FaceDetectionRecognition.cpp ImageQualityDetection.cpp

PROGS		=

all:	$(LIBS) $(PROGS) # test_lib

include ../Makefile.inc
