INCLUDES	=
DEP_INTERNAL	= core json applog
DEP_EXTERNAL	=

LIBS		= rec.a
SRCS_rec	= serialize.cpp fpvc.cpp \
		  model.cpp prototype.cpp multiface.cpp \
		  internal.cpp compare.cpp \
		  prototype_1.cpp cluster_1.cpp multiface_2.cpp multiface_3.cpp

all:	$(LIBS) test_lib

include ../Makefile.inc
