INCLUDES	= -isystem ./frvt/common/src/include
DEP_INTERNAL	= rec_ncnn det_ncnn
DEP_EXTERNAL	= mvec

LIBS		= libfrvt_11.so
SRCS_libfrvt_11	= tester.cpp

ENABLE_STATIC	= 1

PROGS		=

all:	$(LIBS) $(PROGS) # test_lib

include ../Makefile.inc
