INCLUDES        =
DEP_INTERNAL    = det
DEP_EXTERNAL    = tflite
PROGS_INTERNAL	= raw_image_io

LIBS		= det_tflite.a
SRCS_det_tflite	= init.cpp v8_blazeface.cpp mesh478.cpp

all:	$(LIBS) $(EXCLUDED) test_lib

include ../Makefile.inc
