INCLUDES	=
DEP_INTERNAL	= raw_image
DEP_EXTERNAL	=
PROGS_INTERNAL	= json
#PROGS_EXTERNAL	= exif

LIBS = raw_image_3d.a
SRCS_raw_image_3d = camera.cpp io.cpp vrml.cpp fillholes.cpp pointcloud.cpp

all:	$(LIBS) test_lib

include ../Makefile.inc
